---
abstract: 'Access a DBIx::Class Schema from a CGI::Application'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Plugin-DBIx-Class
requires:
  CGI::Application: 0
  DBIx::Class: 0.08108
  FindBin: 0
  SQL::Translator: 0.11002
  Test::Deep: 0
  Test::More: 0.88
  UNIVERSAL: 0
  parent: 0
resources:
  repository: git://github.com/frioux/CGI-Application-Plugin-DBIx-Class.git
version: 1.000101
