---
abstract: 'Access a DBIx::Class Schema from a CGI::Application'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
generated_by: 'Dist::Zilla version 1.100130'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Plugin-DBIx-Class
requires:
  CGI::Application: 0
  CGI::Application::Plugin::DBH: 0
  DBIx::Class: 0.08108
  ExtUtils::MakeMaker: 6.11
  FindBin: 0
  SQL::Translator: 0.11002
  Test::Deep: 0
  Test::More: 0.88
  UNIVERSAL: 0
  parent: 0
resources:
  repository: http://github.com/frioux/CGI-Application-Plugin-DBIx-Class
version: 0.100180
